### ISSUE TITLE
JCarouselLite not working

### ISSUE THREAD

**Issue by querious** [ganeshmax/jcarousellite#6]
Hi there,

I fell in love with your plugin the moment I saw it, with it being so lightweight and perfect for what I need it to do - just to scroll through product image thumbnails. :)

However, I've been trying to get it to work with Opencart but it only seems to scroll once, and that's it. You'll see what I mean here:- http://tinyurl.com/qy4ztyn

I've implemented your code as shown below:-

`<div class="image-additional-left">`
		`<button class="prev">&laquo;</button>`
		`<button class="next">&raquo;</button>`
       `  <div class="carousel94">`
			`<ul>`
				`<?php foreach ($images as $image) { ?>`
				`<li><a href="<?php echo $image['popup']; ?>" title="<?php echo $heading_title; ?>" class="colorbox" rel="colorbox">`
				`<img src="<?php echo $image['thumb']; ?>" width="120" height="120" "title="<?php echo $heading_title; ?>" alt="<?php echo $heading_title; ?>" /></a></li>`
				`<?php } ?>`
			`</ul>`
		`</div>`  
	  `</div>`

	`<script type="text/javascript"></script>`

Am I missing something? 
Just curious, does it work with jquery-1.7.1.min.js?

Hope you could help... Thanks!

**Comment by ganeshmax** [comment]
You are right. Unfortunately, it doesn't seem to work with version 1.7.1 of jquery. I will try to get to it this week, but meanwhile try using a newer version of jquery (if possible).

**Comment by ganeshmax** [comment]
Just did some quick debugging. It seems i am using some features that were added to jquery in version 1.8. I will get to revisiting how to fix it during this week. 

Meanwhile, you have 2 options:
1. Upgrade to a minimum of 1.8 version of jquery 
or 
2. Modify the plugin as given below

Go to                     
```
animateToPosition({         // Animate carousel item to position based on calculated values.
    start: function() {
        running = true;
    },
    done: function() {
        if(options.afterEnd) {
            options.afterEnd.call(this, visibleItems());
        }
        if(options.auto) {
            setupAutoScroll();
        }
        running = false;
    }
});
```

and change it to look like below:

```
animateToPosition({         // Animate carousel item to position based on calculated values.
    complete: function() {
        if(options.afterEnd) {
            options.afterEnd.call(this, visibleItems());
        }
        if(options.auto) {
            setupAutoScroll();
        }
        running = false;
    }
});
```

This should solve your challenge temporarily. Meanwhile once i update the plugin to a new revision, i will keep this issue posted.

**Comment by querious** [comment]
Hi Ganesh,

Thank you so much for your time and effort to look into this issue.

I went with option 2 and modified the plugin as you suggested below. It's
scrolling perfectly now! :)

However, there seems to be a minor glitch though. I'm not entirely sure if
it's something I did wrong, or if you experience the same problem too -
just thought I'd let you know just in case. Now that the scrolling works, I
noticed that I have 15 items in my carousel. In actual fact, I only have 6
images. I double checked the html source code on my page and confirmed that
it only has 6 items in the list too. Just curious how did it end up getting
15 items...

Here is a sample:- http://tinyurl.com/mj7pde2.

Just click on any of the images in the carousel and a popup will appear
with the image enlarged. You'll see at the bottom of the page, it says
"image x of *15*". It's not a critical issue, just that it may be a bit
confusing for the user as there are only 6 images in fact. :)

Again, I can't thank you enough for all your hard work! I've star-ed your
project on GitHub, excellent work!!


Cheers,
Eleni

**Comment by ganeshmax** [comment]
Thanks for your kind words Eleni. 

If your carousel is circular (the default), the algorithm to make it look infintely circular works by adding a clone of your carousel-items to the front and to the back of the carousel . The number of items that get added to the front and the back depends on number of items configured to be visible at any point in time. 

For example, in your case, you have 6 images overall, but you have configured 4 of them to be displayed at a time. So, I need to clone the last 4 (of the 6) images to the front of the carousel and first 4 (of the 6) to the end of the carousel - effectively making the count to 6+4+4 = 14. 

I understand that this behavior is working against the lightbox plugin. I have 2 suggestions. 

1. Make your carousel non-circular by adding the option {circular: false}
2. Try to dig deeper into the light-box plugin and see if you can configure it appropriately

Hope that helps.

**Comment by querious** [comment]
Hi Ganesh,

Thank you again for your quick response! :)

I went with option 1 as you have suggested below, and it's perfect now!!

You've just made my day. I mean, really really made my day. It's really
nice to know that there are people out there like you who are really kind
and helpful. :)

THANK YOU THANK YOU!!! :)

Have a good one and Happy New Year. All the very best to you!!

Cheers,
Eleni

**Comment by ganeshmax** [comment]
my pleasure. 
Closing this defect.

**Comment by querious** [comment]
Hi Ganesh,

I just noticed a weird behavior happening on my website, and I'm not sure
if it's related to the plugin or it's just a CSS issue. Please bear with me
as my CSS skills are rubbish, so I can't really figure out what's wrong
here.

When I implement the carousel, everything looks great on both desktop and
mobile devices. On my desktop, when I reload the page, the carousel loads
the images fine.

However, if I were to reload the page on my mobile device (both iPad and
iPhone), I noticed that all the images in the carousel are overlapping
against each other.

I find it really odd because this only happens when I reload the page on my
mobile devices. Desktop seems fine.

Is there some code in the plugin which may cause this behavior? Here's the
page again:- http://tinyurl.com/mj7pde2.

Hope you could advise... thanks.

Cheers,
Eleni

**Comment by querious** [comment]
Hi Ganesh,

I was wondering if you had a chance to look into this?

Hope you could advise... thanks!

Cheers,
Eleni
